// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFclmE_s47B366NvMCMSbyn-RzHfbubZg',
    appId: '1:374666296461:web:8785cf46238b1b898cf6c4',
    messagingSenderId: '374666296461',
    projectId: 'bloc-struc',
    authDomain: 'bloc-struc.firebaseapp.com',
    storageBucket: 'bloc-struc.firebasestorage.app',
    measurementId: 'G-DMPTLEF5WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZlpFZkbc00ddDj_3SFrTRk68t9ngWvSY',
    appId: '1:374666296461:android:b650e03a13700f868cf6c4',
    messagingSenderId: '374666296461',
    projectId: 'bloc-struc',
    storageBucket: 'bloc-struc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMhgzdH49EqvYKoAIQX_f0BrSl1g0gN70',
    appId: '1:374666296461:ios:1bdb943ad02c726e8cf6c4',
    messagingSenderId: '374666296461',
    projectId: 'bloc-struc',
    storageBucket: 'bloc-struc.firebasestorage.app',
    iosBundleId: 'com.example.blocStruc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMhgzdH49EqvYKoAIQX_f0BrSl1g0gN70',
    appId: '1:374666296461:ios:1bdb943ad02c726e8cf6c4',
    messagingSenderId: '374666296461',
    projectId: 'bloc-struc',
    storageBucket: 'bloc-struc.firebasestorage.app',
    iosBundleId: 'com.example.blocStruc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFclmE_s47B366NvMCMSbyn-RzHfbubZg',
    appId: '1:374666296461:web:52e7322048f4a4ef8cf6c4',
    messagingSenderId: '374666296461',
    projectId: 'bloc-struc',
    authDomain: 'bloc-struc.firebaseapp.com',
    storageBucket: 'bloc-struc.firebasestorage.app',
    measurementId: 'G-634QF58JPX',
  );
}
